services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT_EXTERNAL}:3000
    env_file:
      - frontend/.env
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT_EXTERNAL}:5000
    env_file:
      - backend/.env
  